= osc-doc-framework
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://docs.outscale.com/fr/userguide/_images/Project-Graduated-green.svg[Project Graduated, link="https://docs.outscale.com/en/userguide/Open-Source-Projects.html"]

`osc-doc-framework` is a framework for generating OUTSCALE documentations, and most primarily the https://docs.outscale.com/[OUTSCALE Public Documentation]. It is based on the https://antora.org/[Antora] documentation site generator, with additional custom extensions designed to facilitate the work of technical writers.

In addition to the default Antora features, this framework enables the following:

* API doc generation via https://github.com/Mermade/widdershins/[Widdershins] +
* Prose linting and Style Guide validation via https://vale.sh/[Vale] +
* Search engine via https://gitlab.com/antora/antora-lunr-extension[Antora Lunr Extension] +
* Release note pages with clickable filters +
* 404 page with randomized images +
* RSS feed generation +
* Automatic tooltips +
* ...and more



== Installing

There are multiple ways to install `osc-doc-framework` for your Antora documentation project. If you are an OUTSCALE technical writer, see the README of the internal `userguide` repository for team-specific instructions.

Otherwise, see https://github.com/andrepasteur/antora-repo-example[antora-repo-example] for a working example.




== Linting

You can configure your Git to use the pre-commit hook in the `git-hooks` folder. This pre-commit hook will run https://vale.sh/[Vale] on your the files of your Antora project in order to lint them with the Style Guide rules located in the `Vale/styles` directory.



== Contributing

Feel free to open an issue in case of bugs.



== License

Copyright Outscale SAS

MPL-2.0
